### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HadrienG** [onecodex/finch-rs#11]
Hi again!

I'm more or less done testing the software itself and overall I must say it works well! I'd like to suggest a few improvements to the documentation if you don't mind:

- [x] Although the command-line options are well explained, I think it'd be a good improvement to have a quickstart section with one or two real examples, i.e. "How to compare my samples together?" or "How to quickly compare my samples to RefSeq?"

- [x] You provide sketches for RefSeq (this is great!) but it is not so straight-forward how to query those: `finch dist sketches/refseq_sketches_31_1000/*.sk` fails with `-bash: /Users/hadrien/.cargo/bin/finch: Argument list too long` on my computer. Having a walkthrough on how to do that would improve usability. I used `find` but not sure there isn't a better way.

- [x] There are not guidelines for contributing. Adding a small statement about where to report issues,  how to contribute to your software and eventually a Code of Conduct for people wising to contribute would be - in my opinion - great additions.

Best,
Hadrien.

<hr>

[Review ref for tracking](https://github.com/openjournals/joss-reviews/issues/505)

**Comment by bovee** [comment]
Thanks! These are great suggestions.

I've gone ahead and added a small contribution section to the main README and selected a CODE_OF_CONDUCT (GitHub helpfully makes this very easy).

The first issue is fairly straight-forward, but for the second issue I think this may be a fundamental problem with how we've structured the databases. We should probably merge all of those into one file (because the `bash` problem is upstream of the code we have control over).

**Comment by HadrienG** [comment]
Thanks for your quick reply.

I do not think this is a fundamental problem and as you said what I stumbled upon is a `bash problem`. Of course it would be great to have a unified database or to allow `finch` to take a directory as input in mind for a future release.

For now I think potential users would be more than happy with a short tutorial in the README on how *you* use this databases.

I took the liberty of amending my issue with one more point.


Best,
Hadrien

**Comment by bovee** [comment]
Hi Hadrien,

Sorry for the delay on closing this out (holidays!), but we added a "quick start" to our README and merged together the RefSeq sketches into single files (to fix the glob issue with Bash) in pull request #14, so I think this is complete now. Please let me know if there's anything I missed or if there's anything else you'd like with this.

Best,
Roderick

**Comment by HadrienG** [comment]
Hi!

No worries about the delay. I do not think I have other issues to raise. I'll test again with some example data with `0.1.5` and if it's runs fine I feel comfortable recommending for publication.

Best,
Hadrien
