### ISSUE TITLE
`finch` query/reference selection is confusing

### ISSUE THREAD

**Issue by bovee** [onecodex/finch-rs#24]
Right now we choose whatever is the very last sketch as the "query" and all other as the "references" unless the `-q` flag is passed. This was so we could use the very first sketch as a template for how the other files should be sketched and not require it to be the query, but it ends up being fairly confusing (even for me).

We should instead:
 - Preparse the list and use the first sketch file (if there is one) as the template for any other files that need to be sketched. We probably don't need to allow a parameter to manually choose this file because if you need to do that you can either re-arrange the order or manually specify the sketch parameters.
 - Use the first sketch as the `query` unless manually specified (or should we use _all_ of the sketches in the first file?).
 - Add a `--references` parameter to allow specifying which sketches to use as references.

**Comment by luizirber** [comment]
As an aside, in sourmash we decided to go
`sourmash search <query> <database> [databases ...]`,                
because the usage tends to be querying one dataset against many databases.
